# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-09-11T08:55:01+00:00

from __future__ import annotations

from typing import Annotated, Any, TypeAlias

from msgspec import UNSET, Meta, Struct, UnsetType, field


class VideoSummaryOut(Struct):
    total: Annotated[int, Meta(title='Total')]
    software: Annotated[dict[str, int], Meta(title='Software')]
    level: Annotated[dict[str, int], Meta(title='Level')]
    mode: Annotated[dict[str, int], Meta(title='Mode')]
    state: Annotated[dict[str, int], Meta(title='State')]


class DBTaskResult(Struct):
    enqueued_at: Annotated[str, Meta(title='Enqueued At')]
    args_kwargs: Annotated[dict[str, Any], Meta(title='Args Kwargs')]
    task_path: Annotated[str, Meta(title='Task Path')]
    backend_name: Annotated[str, Meta(max_length=32, title='Backend Name')]
    run_after: Annotated[str, Meta(title='Run After')]
    exception_class_path: Annotated[str, Meta(title='Exception Class Path')]
    traceback: Annotated[str, Meta(title='Traceback')]
    id: Annotated[str, Meta(title='Id')] | None | UnsetType = UNSET
    status: Annotated[str, Meta(max_length=10, title='Status')] | UnsetType = 'READY'
    started_at: Annotated[str, Meta(title='Started At')] | None | UnsetType = UNSET
    finished_at: Annotated[str, Meta(title='Finished At')] | None | UnsetType = UNSET
    priority: Annotated[int, Meta(title='Priority')] | UnsetType = 0
    worker_ids: Annotated[dict[str, Any], Meta(title='Worker Id')] | UnsetType = UNSET
    queue_name: Annotated[str, Meta(max_length=32, title='Queue Name')] | UnsetType = (
        'default'
    )
    return_value: (
        Annotated[dict[str, Any], Meta(title='Return Value')] | None | UnsetType
    ) = UNSET


class RunningTaskHealthOut(Struct):
    id: Annotated[str, Meta(title='Id')]
    task_path: Annotated[str, Meta(title='Task Path')]
    started_at: Annotated[str, Meta(title='Started At')] | None
    age_seconds: Annotated[int, Meta(title='Age Seconds')] | None
    worker_id: Annotated[str, Meta(title='Worker Id')] | None
    worker_state: Annotated[str, Meta(title='Worker State')]
    stale_by_age: Annotated[bool, Meta(title='Stale By Age')]
    probably_orphaned: Annotated[bool, Meta(title='Probably Orphaned')]


class TaskIdIn(Struct):
    task_id: Annotated[str, Meta(title='Task Id')]


class LogFileOut(Struct):
    name: Annotated[str, Meta(title='Name')]
    size: Annotated[int, Meta(title='Size')]
    mtime: Annotated[str, Meta(title='Mtime')]


class LogTailOut(Struct):
    content: Annotated[str, Meta(title='Content')]
    offset: Annotated[int, Meta(title='Offset')]
    size: Annotated[int, Meta(title='Size')]
    truncated: Annotated[bool, Meta(title='Truncated')]


class LogPollOut(Struct):
    content: Annotated[str, Meta(title='Content')]
    offset: Annotated[int, Meta(title='Offset')]
    size: Annotated[int, Meta(title='Size')]
    status: Annotated[str, Meta(title='Status')]


Firstname: TypeAlias = Annotated[str, Meta(max_length=255, title='First Name')]


Lastname: TypeAlias = Annotated[str, Meta(max_length=255, title='Last Name')]


Realname: TypeAlias = Annotated[str, Meta(max_length=100, title='Realname')]


Signature: TypeAlias = Annotated[str, Meta(max_length=4095, title='Signature')]


Signature1: TypeAlias = Annotated[None, Meta(title='Signature')] | None


Country: TypeAlias = Annotated[str, Meta(max_length=2, title='Country')]


class UserProfile(Struct):
    username: Annotated[
        str,
        Meta(
            description='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.',
            max_length=30,
            title='Username',
        ),
    ]
    last_change_avatar: Annotated[str, Meta(title='Last Change Avatar')]
    last_change_signature: Annotated[str, Meta(title='Last Change Signature')]
    id: Annotated[int, Meta(title='ID')] | None | UnsetType = UNSET
    firstname: Annotated[Firstname, Meta(title='First Name')] | None | UnsetType = UNSET
    lastname: Annotated[Lastname, Meta(title='Last Name')] | None | UnsetType = UNSET
    realname: Annotated[Realname, Meta(title='Realname')] | None | UnsetType = '匿名'
    signature: (
        Annotated[Signature | Signature1, Meta(title='Signature')] | None | UnsetType
    ) = ''
    country: Annotated[Country, Meta(title='Country')] | None | UnsetType = ''
    is_banned: Annotated[bool, Meta(title='Is Banned')] | UnsetType = False
    is_staff: (
        Annotated[
            bool,
            Meta(
                description='Designates whether the user can log into this admin site.',
                title='Staff Status',
            ),
        ]
        | UnsetType
    ) = False
    left_avatar_n: Annotated[int, Meta(title='Left Avatar N')] | UnsetType = 2
    left_signature_n: Annotated[int, Meta(title='Left Signature N')] | UnsetType = 2


class VideoModel2(Struct):
    upload_time: Annotated[str, Meta(title='上传时间')]
    level: Annotated[str, Meta(max_length=10, title='Level')]
    software: Annotated[str, Meta(max_length=1, title='Software')]
    cl: Annotated[int, Meta(title='Cl')]
    ce: Annotated[int, Meta(title='Ce')]
    id: Annotated[int, Meta(title='ID')] | None | UnsetType = UNSET
    mode: Annotated[str, Meta(max_length=2, title='Mode')] | UnsetType = '00'
    timems: Annotated[int, Meta(title='Timems')] | UnsetType = 999999
    bv: Annotated[int, Meta(title='Bv')] | None | UnsetType = UNSET
    state: Annotated[str, Meta(max_length=1, title='State')] | UnsetType = 'a'
    file_size: Annotated[int, Meta(title='File Size')] | UnsetType = 0
    end_time: Annotated[str, Meta(title='End Time')] | None | UnsetType = UNSET
    ongoing_tournament: (
        Annotated[bool, Meta(title='Ongoing Tournament')] | UnsetType
    ) = False
    path: Annotated[float, Meta(title='Path')] | None | UnsetType = UNSET
    pluck: Annotated[float, Meta(title='Pluck')] | None | UnsetType = UNSET


class UpdateUserProfileIn(Struct):
    realname: Annotated[str, Meta(title='Realname')] | UnsetType = UNSET
    signature: Annotated[str, Meta(title='Signature')] | UnsetType = UNSET
    firstname: Annotated[str, Meta(title='Firstname')] | UnsetType = UNSET
    lastname: Annotated[str, Meta(title='Lastname')] | UnsetType = UNSET


class AccountBilibili(Struct):
    parent: Annotated[
        int,
        Meta(
            description='OpenMS user linked to this Bilibili account.',
            title='OpenMS user',
        ),
    ]
    update_time: Annotated[
        str,
        Meta(
            description='Time when public Bilibili profile data was last synchronized.',
            title='Update time',
        ),
    ]
    id: (
        Annotated[
            int,
            Meta(
                description='Numeric Bilibili user ID from space.bilibili.com/{uid}.',
                title='Bilibili UID',
            ),
        ]
        | None
        | UnsetType
    ) = UNSET
    name: (
        Annotated[
            str,
            Meta(
                description='Public Bilibili display name.',
                max_length=128,
                title='Display name',
            ),
        ]
        | UnsetType
    ) = ''
    face: (
        Annotated[
            str,
            Meta(
                description='Public Bilibili avatar URL.',
                max_length=500,
                title='Avatar URL',
            ),
        ]
        | UnsetType
    ) = ''
    sign: (
        Annotated[
            str,
            Meta(description='Public Bilibili profile signature.', title='Signature'),
        ]
        | UnsetType
    ) = ''
    level: (
        Annotated[int, Meta(description='Bilibili user level.', title='Level')]
        | UnsetType
    ) = 0
    following: Annotated[int, Meta(title='Following count')] | UnsetType = 0
    follower: Annotated[int, Meta(title='Follower count')] | UnsetType = 0
    video_count: (
        Annotated[
            int,
            Meta(
                description='Number of public video submissions by this Bilibili account.',
                title='Video Count',
            ),
        ]
        | UnsetType
    ) = 0
    article_count: (
        Annotated[
            int,
            Meta(
                description='Number of public article submissions by this Bilibili account.',
                title='Article Count',
            ),
        ]
        | UnsetType
    ) = 0
    opus_count: (
        Annotated[
            int,
            Meta(
                description='Number of public opus/dynamic posts by this Bilibili account.',
                title='Opus Count',
            ),
        ]
        | UnsetType
    ) = 0
    official_title: (
        Annotated[
            str,
            Meta(
                description='Bilibili official verification title, or an empty string when unverified.',
                max_length=128,
                title='Official title',
            ),
        ]
        | UnsetType
    ) = ''


class AccountLinkQueue2(Struct):
    platform: Annotated[str, Meta(max_length=1, title='Platform')]
    identifier: Annotated[str, Meta(max_length=128, title='Identifier')]
    userprofile: Annotated[int, Meta(title='Userprofile')]
    id: Annotated[int, Meta(title='ID')] | None | UnsetType = UNSET
    verified: Annotated[bool, Meta(title='Verified')] | UnsetType = False


class AccountMinesweeperGames(Struct):
    parent: Annotated[int, Meta(title='Parent')]
    update_time: Annotated[str, Meta(title='Update Time')]
    id: Annotated[int, Meta(title='Id')] | None | UnsetType = UNSET
    name: Annotated[str, Meta(max_length=128, title='Name')] | UnsetType = ''
    local_name: Annotated[str, Meta(max_length=128, title='Local Name')] | UnsetType = (
        ''
    )
    joined: Annotated[str, Meta(title='Joined')] | None | UnsetType = UNSET


class AccountQQ(Struct):
    parent: Annotated[int, Meta(title='Parent')]
    id: Annotated[int, Meta(title='Id')] | None | UnsetType = UNSET


class AccountSaolei(Struct):
    parent: Annotated[int, Meta(title='Parent')]
    update_time: Annotated[str, Meta(title='Update Time')]
    id: Annotated[int, Meta(title='Id')] | None | UnsetType = UNSET
    video_import_task: (
        Annotated[str, Meta(title='Video Import Task')] | None | UnsetType
    ) = UNSET
    name: Annotated[str, Meta(max_length=10, title='Name')] | UnsetType = ''
    total_views: Annotated[int, Meta(title='Total Views')] | UnsetType = 0
    beg_count: Annotated[int, Meta(title='Beg Count')] | UnsetType = 0
    int_count: Annotated[int, Meta(title='Int Count')] | UnsetType = 0
    exp_count: Annotated[int, Meta(title='Exp Count')] | UnsetType = 0
    b_t_ms: Annotated[int, Meta(title='B T Ms')] | None | UnsetType = UNSET
    i_t_ms: Annotated[int, Meta(title='I T Ms')] | None | UnsetType = UNSET
    e_t_ms: Annotated[int, Meta(title='E T Ms')] | None | UnsetType = UNSET
    s_t_ms: Annotated[int, Meta(title='S T Ms')] | None | UnsetType = UNSET
    b_b_cent: Annotated[int, Meta(title='B B Cent')] | None | UnsetType = UNSET
    i_b_cent: Annotated[int, Meta(title='I B Cent')] | None | UnsetType = UNSET
    e_b_cent: Annotated[int, Meta(title='E B Cent')] | None | UnsetType = UNSET
    s_b_cent: Annotated[int, Meta(title='S B Cent')] | None | UnsetType = UNSET


class AccountWorldOfMinesweeper(Struct):
    parent: Annotated[int, Meta(title='Parent')]
    update_time: Annotated[str, Meta(title='Update Time')]
    id: Annotated[int, Meta(title='Id')] | None | UnsetType = UNSET
    trophy: Annotated[int, Meta(title='Trophy')] | None | UnsetType = UNSET
    experience: Annotated[int, Meta(title='Experience')] | None | UnsetType = UNSET
    honour: Annotated[int, Meta(title='Honour')] | None | UnsetType = UNSET
    minecoin: Annotated[int, Meta(title='Minecoin')] | None | UnsetType = UNSET
    gem: Annotated[int, Meta(title='Gem')] | None | UnsetType = UNSET
    coin: Annotated[int, Meta(title='Coin')] | None | UnsetType = UNSET
    arena_ticket: Annotated[int, Meta(title='Arena Ticket')] | None | UnsetType = UNSET
    equipment: Annotated[int, Meta(title='Equipment')] | None | UnsetType = UNSET
    part: Annotated[int, Meta(title='Part')] | None | UnsetType = UNSET
    arena_point: Annotated[int, Meta(title='Arena Point')] | None | UnsetType = UNSET
    max_difficulty: Annotated[int, Meta(title='Max Difficulty')] | None | UnsetType = (
        UNSET
    )
    win: Annotated[int, Meta(title='Win')] | None | UnsetType = UNSET
    last_season: Annotated[int, Meta(title='Last Season')] | None | UnsetType = UNSET
    b_t_ms: Annotated[int, Meta(title='B T Ms')] | None | UnsetType = UNSET
    i_t_ms: Annotated[int, Meta(title='I T Ms')] | None | UnsetType = UNSET
    e_t_ms: Annotated[int, Meta(title='E T Ms')] | None | UnsetType = UNSET
    b_ioe: Annotated[float, Meta(title='B Ioe')] | None | UnsetType = UNSET
    i_ioe: Annotated[float, Meta(title='I Ioe')] | None | UnsetType = UNSET
    e_ioe: Annotated[float, Meta(title='E Ioe')] | None | UnsetType = UNSET
    b_mastery: Annotated[int, Meta(title='B Mastery')] | None | UnsetType = UNSET
    i_mastery: Annotated[int, Meta(title='I Mastery')] | None | UnsetType = UNSET
    e_mastery: Annotated[int, Meta(title='E Mastery')] | None | UnsetType = UNSET
    b_winstreak: Annotated[int, Meta(title='B Winstreak')] | None | UnsetType = UNSET
    i_winstreak: Annotated[int, Meta(title='I Winstreak')] | None | UnsetType = UNSET
    e_winstreak: Annotated[int, Meta(title='E Winstreak')] | None | UnsetType = UNSET


class AccountLinkQueue(Struct):
    platform: Annotated[str, Meta(max_length=1, title='Platform')]
    identifier: Annotated[str, Meta(max_length=128, title='Identifier')]
    userprofile: Annotated[int, Meta(title='Userprofile')]
    id: Annotated[int, Meta(title='ID')] | None | UnsetType = UNSET
    verified: Annotated[bool, Meta(title='Verified')] | UnsetType = False


class AccountLinkCreateIn(Struct):
    platform: Annotated[str, Meta(title='Platform')]
    identifier: Annotated[str, Meta(title='Identifier')]


class VideoModel(Struct):
    player: Annotated[int, Meta(title='Player')]
    software: Annotated[str, Meta(max_length=1, title='Software')]
    level: Annotated[str, Meta(max_length=10, title='Level')]
    cl: Annotated[int, Meta(title='Cl')]
    ce: Annotated[int, Meta(title='Ce')]
    upload_time: Annotated[str, Meta(title='上传时间')]
    id: Annotated[int, Meta(title='ID')] | None | UnsetType = UNSET
    mode: Annotated[str, Meta(max_length=2, title='Mode')] | UnsetType = '00'
    state: Annotated[str, Meta(max_length=1, title='State')] | UnsetType = 'a'
    timems: Annotated[int, Meta(title='Timems')] | UnsetType = 999999
    bv: Annotated[int, Meta(title='Bv')] | None | UnsetType = UNSET
    end_time: Annotated[str, Meta(title='End Time')] | None | UnsetType = UNSET


class VideoModel3(Struct):
    player: Annotated[int, Meta(title='Player')]
    software: Annotated[str, Meta(max_length=1, title='Software')]
    level: Annotated[str, Meta(max_length=10, title='Level')]
    upload_time: Annotated[str, Meta(title='上传时间')]
    cl: Annotated[int, Meta(title='Cl')]
    ce: Annotated[int, Meta(title='Ce')]
    id: Annotated[int, Meta(title='ID')] | None | UnsetType = UNSET
    mode: Annotated[str, Meta(max_length=2, title='Mode')] | UnsetType = '00'
    state: Annotated[str, Meta(max_length=1, title='State')] | UnsetType = 'a'
    timems: Annotated[int, Meta(title='Timems')] | UnsetType = 999999
    bv: Annotated[int, Meta(title='Bv')] | None | UnsetType = UNSET
    path: Annotated[float, Meta(title='Path')] | None | UnsetType = UNSET
    flag: Annotated[int, Meta(title='Flag')] | None | UnsetType = UNSET
    op: Annotated[int, Meta(title='Op')] | None | UnsetType = UNSET
    isl: Annotated[int, Meta(title='Isl')] | None | UnsetType = UNSET
    end_time: Annotated[str, Meta(title='End Time')] | None | UnsetType = UNSET
    file_size: Annotated[int, Meta(title='File Size')] | UnsetType = 0
    left: Annotated[int, Meta(title='Left')] | None | UnsetType = UNSET
    right: Annotated[int, Meta(title='Right')] | None | UnsetType = UNSET
    double: Annotated[int, Meta(title='Double')] | None | UnsetType = UNSET
    left_ce: Annotated[int, Meta(title='Left Ce')] | None | UnsetType = UNSET
    right_ce: Annotated[int, Meta(title='Right Ce')] | None | UnsetType = UNSET
    double_ce: Annotated[int, Meta(title='Double Ce')] | None | UnsetType = UNSET
    cell0: Annotated[int, Meta(title='Cell0')] | None | UnsetType = UNSET
    cell1: Annotated[int, Meta(title='Cell1')] | None | UnsetType = UNSET
    cell2: Annotated[int, Meta(title='Cell2')] | None | UnsetType = UNSET
    cell3: Annotated[int, Meta(title='Cell3')] | None | UnsetType = UNSET
    cell4: Annotated[int, Meta(title='Cell4')] | None | UnsetType = UNSET
    cell5: Annotated[int, Meta(title='Cell5')] | None | UnsetType = UNSET
    cell6: Annotated[int, Meta(title='Cell6')] | None | UnsetType = UNSET
    cell7: Annotated[int, Meta(title='Cell7')] | None | UnsetType = UNSET
    cell8: Annotated[int, Meta(title='Cell8')] | None | UnsetType = UNSET
    video__identifier: Annotated[str, Meta(title='Video  Identifier')] | UnsetType = ''


class CustomPluckPlayerOut(Struct):
    player_id: Annotated[int, Meta(title='Player Id')]
    video_id: Annotated[int, Meta(title='Video Id')]
    mode: Annotated[str, Meta(title='Mode')]
    pluck: Annotated[float, Meta(title='Pluck')]
    timems: Annotated[int, Meta(title='Timems')]
    bv: Annotated[int, Meta(title='Bv')]
    upload_time: Annotated[str, Meta(title='Upload Time')]


class CustomPluckRankOut(Struct):
    count: Annotated[int, Meta(title='Count')]
    players: Annotated[list[CustomPluckPlayerOut], Meta(title='Players')]


class CustomPluckRecordOut(Struct):
    level: Annotated[str, Meta(title='Level')]
    video_id: Annotated[int, Meta(title='Video Id')]
    pluck: Annotated[float, Meta(title='Pluck')]


class RefreshCustomPluckRankOut(Struct):
    errorList: Annotated[list[int], Meta(title='Errorlist')]
    successCount: Annotated[int, Meta(title='Successcount')]


class RefreshCustomPluckRankIn(Struct):
    startid: Annotated[int, Meta(title='Startid')]
    endid: Annotated[int, Meta(title='Endid')]


class UserMS(Struct):
    b_timems_std: Annotated[int, Meta(title='B Timems Std')] | UnsetType = 999999
    b_timems_id_std: (
        Annotated[int, Meta(title='B Timems Id Std')] | None | UnsetType
    ) = UNSET
    i_timems_std: Annotated[int, Meta(title='I Timems Std')] | UnsetType = 999999
    i_timems_id_std: (
        Annotated[int, Meta(title='I Timems Id Std')] | None | UnsetType
    ) = UNSET
    e_timems_std: Annotated[int, Meta(title='E Timems Std')] | UnsetType = 999999
    e_timems_id_std: (
        Annotated[int, Meta(title='E Timems Id Std')] | None | UnsetType
    ) = UNSET
    b_bvs_std: Annotated[float, Meta(title='B Bvs Std')] | UnsetType = 0.0
    b_bvs_id_std: Annotated[int, Meta(title='B Bvs Id Std')] | None | UnsetType = UNSET
    i_bvs_std: Annotated[float, Meta(title='I Bvs Std')] | UnsetType = 0.0
    i_bvs_id_std: Annotated[int, Meta(title='I Bvs Id Std')] | None | UnsetType = UNSET
    e_bvs_std: Annotated[float, Meta(title='E Bvs Std')] | UnsetType = 0.0
    e_bvs_id_std: Annotated[int, Meta(title='E Bvs Id Std')] | None | UnsetType = UNSET
    b_stnb_std: Annotated[float, Meta(title='B Stnb Std')] | UnsetType = 0.0
    b_stnb_id_std: Annotated[int, Meta(title='B Stnb Id Std')] | None | UnsetType = (
        UNSET
    )
    i_stnb_std: Annotated[float, Meta(title='I Stnb Std')] | UnsetType = 0.0
    i_stnb_id_std: Annotated[int, Meta(title='I Stnb Id Std')] | None | UnsetType = (
        UNSET
    )
    e_stnb_std: Annotated[float, Meta(title='E Stnb Std')] | UnsetType = 0.0
    e_stnb_id_std: Annotated[int, Meta(title='E Stnb Id Std')] | None | UnsetType = (
        UNSET
    )
    b_ioe_std: Annotated[float, Meta(title='B Ioe Std')] | UnsetType = 0.0
    b_ioe_id_std: Annotated[int, Meta(title='B Ioe Id Std')] | None | UnsetType = UNSET
    i_ioe_std: Annotated[float, Meta(title='I Ioe Std')] | UnsetType = 0.0
    i_ioe_id_std: Annotated[int, Meta(title='I Ioe Id Std')] | None | UnsetType = UNSET
    e_ioe_std: Annotated[float, Meta(title='E Ioe Std')] | UnsetType = 0.0
    e_ioe_id_std: Annotated[int, Meta(title='E Ioe Id Std')] | None | UnsetType = UNSET
    b_path_std: Annotated[float, Meta(title='B Path Std')] | UnsetType = 100000.0
    b_path_id_std: Annotated[int, Meta(title='B Path Id Std')] | None | UnsetType = (
        UNSET
    )
    i_path_std: Annotated[float, Meta(title='I Path Std')] | UnsetType = 100000.0
    i_path_id_std: Annotated[int, Meta(title='I Path Id Std')] | None | UnsetType = (
        UNSET
    )
    e_path_std: Annotated[float, Meta(title='E Path Std')] | UnsetType = 100000.0
    e_path_id_std: Annotated[int, Meta(title='E Path Id Std')] | None | UnsetType = (
        UNSET
    )
    b_timems_nf: Annotated[int, Meta(title='B Timems Nf')] | UnsetType = 999999
    b_timems_id_nf: Annotated[int, Meta(title='B Timems Id Nf')] | None | UnsetType = (
        UNSET
    )
    i_timems_nf: Annotated[int, Meta(title='I Timems Nf')] | UnsetType = 999999
    i_timems_id_nf: Annotated[int, Meta(title='I Timems Id Nf')] | None | UnsetType = (
        UNSET
    )
    e_timems_nf: Annotated[int, Meta(title='E Timems Nf')] | UnsetType = 999999
    e_timems_id_nf: Annotated[int, Meta(title='E Timems Id Nf')] | None | UnsetType = (
        UNSET
    )
    b_bvs_nf: Annotated[float, Meta(title='B Bvs Nf')] | UnsetType = 0.0
    b_bvs_id_nf: Annotated[int, Meta(title='B Bvs Id Nf')] | None | UnsetType = UNSET
    i_bvs_nf: Annotated[float, Meta(title='I Bvs Nf')] | UnsetType = 0.0
    i_bvs_id_nf: Annotated[int, Meta(title='I Bvs Id Nf')] | None | UnsetType = UNSET
    e_bvs_nf: Annotated[float, Meta(title='E Bvs Nf')] | UnsetType = 0.0
    e_bvs_id_nf: Annotated[int, Meta(title='E Bvs Id Nf')] | None | UnsetType = UNSET
    b_stnb_nf: Annotated[float, Meta(title='B Stnb Nf')] | UnsetType = 0.0
    b_stnb_id_nf: Annotated[int, Meta(title='B Stnb Id Nf')] | None | UnsetType = UNSET
    i_stnb_nf: Annotated[float, Meta(title='I Stnb Nf')] | UnsetType = 0.0
    i_stnb_id_nf: Annotated[int, Meta(title='I Stnb Id Nf')] | None | UnsetType = UNSET
    e_stnb_nf: Annotated[float, Meta(title='E Stnb Nf')] | UnsetType = 0.0
    e_stnb_id_nf: Annotated[int, Meta(title='E Stnb Id Nf')] | None | UnsetType = UNSET
    b_ioe_nf: Annotated[float, Meta(title='B Ioe Nf')] | UnsetType = 0.0
    b_ioe_id_nf: Annotated[int, Meta(title='B Ioe Id Nf')] | None | UnsetType = UNSET
    i_ioe_nf: Annotated[float, Meta(title='I Ioe Nf')] | UnsetType = 0.0
    i_ioe_id_nf: Annotated[int, Meta(title='I Ioe Id Nf')] | None | UnsetType = UNSET
    e_ioe_nf: Annotated[float, Meta(title='E Ioe Nf')] | UnsetType = 0.0
    e_ioe_id_nf: Annotated[int, Meta(title='E Ioe Id Nf')] | None | UnsetType = UNSET
    b_path_nf: Annotated[float, Meta(title='B Path Nf')] | UnsetType = 100000.0
    b_path_id_nf: Annotated[int, Meta(title='B Path Id Nf')] | None | UnsetType = UNSET
    i_path_nf: Annotated[float, Meta(title='I Path Nf')] | UnsetType = 100000.0
    i_path_id_nf: Annotated[int, Meta(title='I Path Id Nf')] | None | UnsetType = UNSET
    e_path_nf: Annotated[float, Meta(title='E Path Nf')] | UnsetType = 100000.0
    e_path_id_nf: Annotated[int, Meta(title='E Path Id Nf')] | None | UnsetType = UNSET
    b_timems_ng: Annotated[int, Meta(title='B Timems Ng')] | UnsetType = 999999
    b_timems_id_ng: Annotated[int, Meta(title='B Timems Id Ng')] | None | UnsetType = (
        UNSET
    )
    i_timems_ng: Annotated[int, Meta(title='I Timems Ng')] | UnsetType = 999999
    i_timems_id_ng: Annotated[int, Meta(title='I Timems Id Ng')] | None | UnsetType = (
        UNSET
    )
    e_timems_ng: Annotated[int, Meta(title='E Timems Ng')] | UnsetType = 999999
    e_timems_id_ng: Annotated[int, Meta(title='E Timems Id Ng')] | None | UnsetType = (
        UNSET
    )
    b_bvs_ng: Annotated[float, Meta(title='B Bvs Ng')] | UnsetType = 0.0
    b_bvs_id_ng: Annotated[int, Meta(title='B Bvs Id Ng')] | None | UnsetType = UNSET
    i_bvs_ng: Annotated[float, Meta(title='I Bvs Ng')] | UnsetType = 0.0
    i_bvs_id_ng: Annotated[int, Meta(title='I Bvs Id Ng')] | None | UnsetType = UNSET
    e_bvs_ng: Annotated[float, Meta(title='E Bvs Ng')] | UnsetType = 0.0
    e_bvs_id_ng: Annotated[int, Meta(title='E Bvs Id Ng')] | None | UnsetType = UNSET
    b_stnb_ng: Annotated[float, Meta(title='B Stnb Ng')] | UnsetType = 0.0
    b_stnb_id_ng: Annotated[int, Meta(title='B Stnb Id Ng')] | None | UnsetType = UNSET
    i_stnb_ng: Annotated[float, Meta(title='I Stnb Ng')] | UnsetType = 0.0
    i_stnb_id_ng: Annotated[int, Meta(title='I Stnb Id Ng')] | None | UnsetType = UNSET
    e_stnb_ng: Annotated[float, Meta(title='E Stnb Ng')] | UnsetType = 0.0
    e_stnb_id_ng: Annotated[int, Meta(title='E Stnb Id Ng')] | None | UnsetType = UNSET
    b_ioe_ng: Annotated[float, Meta(title='B Ioe Ng')] | UnsetType = 0.0
    b_ioe_id_ng: Annotated[int, Meta(title='B Ioe Id Ng')] | None | UnsetType = UNSET
    i_ioe_ng: Annotated[float, Meta(title='I Ioe Ng')] | UnsetType = 0.0
    i_ioe_id_ng: Annotated[int, Meta(title='I Ioe Id Ng')] | None | UnsetType = UNSET
    e_ioe_ng: Annotated[float, Meta(title='E Ioe Ng')] | UnsetType = 0.0
    e_ioe_id_ng: Annotated[int, Meta(title='E Ioe Id Ng')] | None | UnsetType = UNSET
    b_path_ng: Annotated[float, Meta(title='B Path Ng')] | UnsetType = 100000.0
    b_path_id_ng: Annotated[int, Meta(title='B Path Id Ng')] | None | UnsetType = UNSET
    i_path_ng: Annotated[float, Meta(title='I Path Ng')] | UnsetType = 100000.0
    i_path_id_ng: Annotated[int, Meta(title='I Path Id Ng')] | None | UnsetType = UNSET
    e_path_ng: Annotated[float, Meta(title='E Path Ng')] | UnsetType = 100000.0
    e_path_id_ng: Annotated[int, Meta(title='E Path Id Ng')] | None | UnsetType = UNSET
    b_timems_dg: Annotated[int, Meta(title='B Timems Dg')] | UnsetType = 999999
    b_timems_id_dg: Annotated[int, Meta(title='B Timems Id Dg')] | None | UnsetType = (
        UNSET
    )
    i_timems_dg: Annotated[int, Meta(title='I Timems Dg')] | UnsetType = 999999
    i_timems_id_dg: Annotated[int, Meta(title='I Timems Id Dg')] | None | UnsetType = (
        UNSET
    )
    e_timems_dg: Annotated[int, Meta(title='E Timems Dg')] | UnsetType = 999999
    e_timems_id_dg: Annotated[int, Meta(title='E Timems Id Dg')] | None | UnsetType = (
        UNSET
    )
    b_bvs_dg: Annotated[float, Meta(title='B Bvs Dg')] | UnsetType = 0.0
    b_bvs_id_dg: Annotated[int, Meta(title='B Bvs Id Dg')] | None | UnsetType = UNSET
    i_bvs_dg: Annotated[float, Meta(title='I Bvs Dg')] | UnsetType = 0.0
    i_bvs_id_dg: Annotated[int, Meta(title='I Bvs Id Dg')] | None | UnsetType = UNSET
    e_bvs_dg: Annotated[float, Meta(title='E Bvs Dg')] | UnsetType = 0.0
    e_bvs_id_dg: Annotated[int, Meta(title='E Bvs Id Dg')] | None | UnsetType = UNSET
    b_stnb_dg: Annotated[float, Meta(title='B Stnb Dg')] | UnsetType = 0.0
    b_stnb_id_dg: Annotated[int, Meta(title='B Stnb Id Dg')] | None | UnsetType = UNSET
    i_stnb_dg: Annotated[float, Meta(title='I Stnb Dg')] | UnsetType = 0.0
    i_stnb_id_dg: Annotated[int, Meta(title='I Stnb Id Dg')] | None | UnsetType = UNSET
    e_stnb_dg: Annotated[float, Meta(title='E Stnb Dg')] | UnsetType = 0.0
    e_stnb_id_dg: Annotated[int, Meta(title='E Stnb Id Dg')] | None | UnsetType = UNSET
    b_ioe_dg: Annotated[float, Meta(title='B Ioe Dg')] | UnsetType = 0.0
    b_ioe_id_dg: Annotated[int, Meta(title='B Ioe Id Dg')] | None | UnsetType = UNSET
    i_ioe_dg: Annotated[float, Meta(title='I Ioe Dg')] | UnsetType = 0.0
    i_ioe_id_dg: Annotated[int, Meta(title='I Ioe Id Dg')] | None | UnsetType = UNSET
    e_ioe_dg: Annotated[float, Meta(title='E Ioe Dg')] | UnsetType = 0.0
    e_ioe_id_dg: Annotated[int, Meta(title='E Ioe Id Dg')] | None | UnsetType = UNSET
    b_path_dg: Annotated[float, Meta(title='B Path Dg')] | UnsetType = 100000.0
    b_path_id_dg: Annotated[int, Meta(title='B Path Id Dg')] | None | UnsetType = UNSET
    i_path_dg: Annotated[float, Meta(title='I Path Dg')] | UnsetType = 100000.0
    i_path_id_dg: Annotated[int, Meta(title='I Path Id Dg')] | None | UnsetType = UNSET
    e_path_dg: Annotated[float, Meta(title='E Path Dg')] | UnsetType = 100000.0
    e_path_id_dg: Annotated[int, Meta(title='E Path Id Dg')] | None | UnsetType = UNSET


class UserMS2(Struct):
    b_timems_std: Annotated[int, Meta(title='B Timems Std')] | UnsetType = 999999
    b_timems_id_std: (
        Annotated[int, Meta(title='B Timems Id Std')] | None | UnsetType
    ) = UNSET
    i_timems_std: Annotated[int, Meta(title='I Timems Std')] | UnsetType = 999999
    i_timems_id_std: (
        Annotated[int, Meta(title='I Timems Id Std')] | None | UnsetType
    ) = UNSET
    e_timems_std: Annotated[int, Meta(title='E Timems Std')] | UnsetType = 999999
    e_timems_id_std: (
        Annotated[int, Meta(title='E Timems Id Std')] | None | UnsetType
    ) = UNSET
    b_bvs_std: Annotated[float, Meta(title='B Bvs Std')] | UnsetType = 0.0
    b_bvs_id_std: Annotated[int, Meta(title='B Bvs Id Std')] | None | UnsetType = UNSET
    i_bvs_std: Annotated[float, Meta(title='I Bvs Std')] | UnsetType = 0.0
    i_bvs_id_std: Annotated[int, Meta(title='I Bvs Id Std')] | None | UnsetType = UNSET
    e_bvs_std: Annotated[float, Meta(title='E Bvs Std')] | UnsetType = 0.0
    e_bvs_id_std: Annotated[int, Meta(title='E Bvs Id Std')] | None | UnsetType = UNSET


class Tournament(Struct):
    id: Annotated[int, Meta(title='ID')] | None | UnsetType = UNSET
    start_time: Annotated[str, Meta(title='Start Time')] | None | UnsetType = UNSET
    end_time: Annotated[str, Meta(title='End Time')] | None | UnsetType = UNSET
    state: Annotated[str, Meta(max_length=1, title='State')] | UnsetType = 'p'
    subclass: Annotated[str, Meta(max_length=1, title='Subclass')] | UnsetType = 'g'
    host_id: Annotated[int, Meta(title='Host Id')] | None | UnsetType = UNSET
    data: Annotated[Any, Meta(title='Data')] | UnsetType = field(default_factory=dict)


class TournamentSetIn(Struct):
    id: Annotated[int, Meta(title='Id')]
    start_time: Annotated[str, Meta(title='Start Time')] | None | UnsetType = UNSET
    end_time: Annotated[str, Meta(title='End Time')] | None | UnsetType = UNSET
    order: Annotated[int, Meta(title='Order')] | None | UnsetType = UNSET
    token: Annotated[str, Meta(title='Token')] | None | UnsetType = UNSET


class TournamentValidationIn(Struct):
    id: Annotated[int, Meta(title='Id')]
    valid: Annotated[bool, Meta(title='Valid')]


class IdIn(Struct):
    id: Annotated[int, Meta(title='Id')]


class TournamentStaffSetIn(Struct):
    tournament_id: Annotated[int, Meta(title='Tournament Id')]
    weight: Annotated[int, Meta(title='Weight')] | None | UnsetType = UNSET
    host_id: Annotated[int, Meta(title='Host Id')] | None | UnsetType = UNSET


class TournamentParticipant(Struct):
    token: Annotated[str, Meta(max_length=80, title='Token')]
    id: Annotated[int, Meta(title='ID')] | None | UnsetType = UNSET
    start_time: Annotated[str, Meta(title='Start Time')] | UnsetType = UNSET
    end_time: Annotated[str, Meta(title='End Time')] | None | UnsetType = UNSET
    rank: Annotated[int, Meta(title='Rank')] | None | UnsetType = UNSET
    rank_score: Annotated[int, Meta(title='Rank Score')] | UnsetType = 0
    user_id: Annotated[int, Meta(title='User Id')] | UnsetType = 0
    tournament_id: Annotated[int, Meta(title='Tournament Id')] | UnsetType = 0
    arbiter_identifier__identifier: (
        Annotated[str, Meta(title='Arbiter Identifier  Identifier')] | None | UnsetType
    ) = UNSET


class TournamentUser(Struct):
    score_current: Annotated[float, Meta(title='Score Current')] | UnsetType = 0
    last_updated: Annotated[str, Meta(title='Last Updated')] | UnsetType = UNSET
    score_total: Annotated[int, Meta(title='Score Total')] | UnsetType = 0
    gsc_total: Annotated[int, Meta(title='Gsc Total')] | UnsetType = 0
    gsc_best: Annotated[int, Meta(title='Gsc Best')] | UnsetType = 9223372036854775807
    weekly_total: Annotated[int, Meta(title='Weekly Total')] | UnsetType = 0
    weekly_classic_total: (
        Annotated[int, Meta(title='Weekly Classic Total')] | UnsetType
    ) = 0
    weekly_classic_best: (
        Annotated[int, Meta(title='Weekly Classic Best')] | UnsetType
    ) = 9223372036854775807
    user_id: Annotated[int, Meta(title='User Id')] | UnsetType = 0


class TournamentUserRankingOut(Struct):
    total: Annotated[int, Meta(title='Total')]
    data: Annotated[list[TournamentUser], Meta(title='Data')]


class TournamentNewsItemOut(Struct):
    id: Annotated[int, Meta(title='Id')]
    start_time: Annotated[str, Meta(title='Start Time')] | None | UnsetType = UNSET
    end_time: Annotated[str, Meta(title='End Time')] | None | UnsetType = UNSET


class TournamentNewsOut(Struct):
    preparing: Annotated[list[TournamentNewsItemOut], Meta(title='Preparing')]
    ongoing: Annotated[list[TournamentNewsItemOut], Meta(title='Ongoing')]


class NewGSCTournamentIn(Struct):
    id: Annotated[int, Meta(title='Id')]
    start_time: Annotated[str, Meta(title='Start Time')] | None | UnsetType = UNSET
    end_time: Annotated[str, Meta(title='End Time')] | None | UnsetType = UNSET


class GSCTournament(Struct):
    id: Annotated[int, Meta(title='ID')] | None | UnsetType = UNSET
    order: Annotated[int, Meta(title='Order')] | None | UnsetType = UNSET
    start_time: Annotated[str, Meta(title='Start Time')] | None | UnsetType = UNSET
    end_time: Annotated[str, Meta(title='End Time')] | None | UnsetType = UNSET
    state: Annotated[str, Meta(max_length=1, title='State')] | UnsetType = 'p'
    token: Annotated[str, Meta(title='Token')] | UnsetType = ''


class GSCParticipant(Struct):
    id: Annotated[int, Meta(title='ID')] | None | UnsetType = UNSET
    start_time: Annotated[str, Meta(title='Start Time')] | UnsetType = UNSET
    end_time: Annotated[str, Meta(title='End Time')] | None | UnsetType = UNSET
    rank: Annotated[int, Meta(title='Rank')] | None | UnsetType = UNSET
    rank_score: Annotated[int, Meta(title='Rank Score')] | UnsetType = 0
    bt1st: Annotated[int, Meta(title='Bt1St')] | UnsetType = 10000
    bt20th: Annotated[int, Meta(title='Bt20Th')] | UnsetType = 10000
    bt20sum: Annotated[int, Meta(title='Bt20Sum')] | UnsetType = 200000
    it1st: Annotated[int, Meta(title='It1St')] | UnsetType = 60000
    it12th: Annotated[int, Meta(title='It12Th')] | UnsetType = 60000
    it12sum: Annotated[int, Meta(title='It12Sum')] | UnsetType = 720000
    et1st: Annotated[int, Meta(title='Et1St')] | UnsetType = 240000
    et5th: Annotated[int, Meta(title='Et5Th')] | UnsetType = 240000
    et5sum: Annotated[int, Meta(title='Et5Sum')] | UnsetType = 1200000
    user_id: Annotated[int, Meta(title='User Id')] | UnsetType = 0


class GSCOrderIn(Struct):
    order: Annotated[int, Meta(title='Order')]


class RegisterGSCParticipantIn(Struct):
    identifier: Annotated[str, Meta(title='Identifier')]
    order: Annotated[int, Meta(title='Order')]


class DBTaskResult2(Struct):
    enqueued_at: Annotated[str, Meta(title='Enqueued At')]
    run_after: Annotated[str, Meta(title='Run After')]
    exception_class_path: Annotated[str, Meta(title='Exception Class Path')]
    traceback: Annotated[str, Meta(title='Traceback')]
    id: Annotated[str, Meta(title='Id')] | None | UnsetType = UNSET
    status: Annotated[str, Meta(max_length=10, title='Status')] | UnsetType = 'READY'
    started_at: Annotated[str, Meta(title='Started At')] | None | UnsetType = UNSET
    finished_at: Annotated[str, Meta(title='Finished At')] | None | UnsetType = UNSET
    return_value: (
        Annotated[dict[str, Any], Meta(title='Return Value')] | None | UnsetType
    ) = UNSET


class WeeklyTournament(Struct):
    year: Annotated[int, Meta(title='Year')]
    week: Annotated[int, Meta(title='Week')]
    id: Annotated[int, Meta(title='ID')] | None | UnsetType = UNSET
    start_time: Annotated[str, Meta(title='Start Time')] | None | UnsetType = UNSET
    end_time: Annotated[str, Meta(title='End Time')] | None | UnsetType = UNSET
    state: Annotated[str, Meta(max_length=1, title='State')] | UnsetType = 'p'
    tournament_format: (
        Annotated[str, Meta(max_length=1, title='Tournament Format')] | UnsetType
    ) = 'c'


class NewWeeklyTournamentIn(Struct):
    tournament_format: Annotated[str, Meta(title='Tournament Format')] | UnsetType = 'c'


class WeeklySetIn(Struct):
    id: Annotated[int, Meta(title='Id')]
    state: Annotated[str, Meta(title='State')]


class WeeklyParticipant(Struct):
    id: Annotated[int, Meta(title='ID')] | None | UnsetType = UNSET
    start_time: Annotated[str, Meta(title='Start Time')] | UnsetType = UNSET
    end_time: Annotated[str, Meta(title='End Time')] | None | UnsetType = UNSET
    rank: Annotated[int, Meta(title='Rank')] | None | UnsetType = UNSET
    rank_score: Annotated[int, Meta(title='Rank Score')] | UnsetType = 0
    classic_et: Annotated[dict[str, Any], Meta(title='Classic Et')] | UnsetType = UNSET
    classic_it: Annotated[dict[str, Any], Meta(title='Classic It')] | UnsetType = UNSET
    classic_score: Annotated[int, Meta(title='Classic Score')] | UnsetType = 780000
    user_id: Annotated[int, Meta(title='User Id')] | UnsetType = 0


class WeeklyParticipant2(Struct):
    token: Annotated[str, Meta(max_length=80, title='Token')]
    id: Annotated[int, Meta(title='ID')] | None | UnsetType = UNSET
    start_time: Annotated[str, Meta(title='Start Time')] | UnsetType = UNSET
    end_time: Annotated[str, Meta(title='End Time')] | None | UnsetType = UNSET
    rank: Annotated[int, Meta(title='Rank')] | None | UnsetType = UNSET
    rank_score: Annotated[int, Meta(title='Rank Score')] | UnsetType = 0
    user_id: Annotated[int, Meta(title='User Id')] | UnsetType = 0
    tournament_id: Annotated[int, Meta(title='Tournament Id')] | UnsetType = 0


class AccountLinkCompleteOut(Struct):
    summary: Annotated[list[AccountLinkQueue2], Meta(title='Summary')]
    B: AccountBilibili | None | UnsetType = UNSET
    c: AccountSaolei | None | UnsetType = UNSET
    a: AccountMinesweeperGames | None | UnsetType = UNSET
    w: AccountWorldOfMinesweeper | None | UnsetType = UNSET
    q: AccountQQ | None | UnsetType = UNSET


class NewWeeklyTournamentOut(Struct):
    data: WeeklyTournament
