[package]
name = "ms-toollib"
version = "1.0.5"
edition = "2018"
authors = ["Wang Jianing <wangjianing@88.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[dependencies.rayon]
#version = "1.1"

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]

[dependencies.rand]
version = "0.8.3"

[dependencies.itertools]
version = "0.10.0"

[lib]
name = "ms_toollib"
crate-type = ["cdylib"]






