# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build Blackcat

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pyinstaller
        pip install -r requirements.txt

    - name: Install Rust dependencies
      run: |
        cd toollib
        cargo build --release
        cd ..
        toollib/target/release/ms_toollib.dll src/ms_toollib.pyd

    # stop the build if there are Python syntax errors or undefined names
    - name: Lint with flake8
      run: |
        flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Package with PyInstaller
      run: |
        pyinstaller -i cat.ico -w -y --clean --add-data "./media/*;./media" -p src src/main.py

    # upload the result package as an artifact
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: blackcat-snapshot
        path: dist/main/
